# """
# services/avatar.py  —  Talking Avatar Service
# ═══════════════════════════════════════════════════════════════════════════════

# Two modes:
#   FREE     — FLUX.1 generates a face image, Wav2Lip animates it
#   PREMIUM  — User uploads their own photo, Wav2Lip animates it

# Animation fallback chain:
#   1. manavisrani07/gradio-lipsync-wav2lip  (primary — regular GPU Space)
#   2. pragnakalp/Wav2lip-ZeroGPU            (secondary — ZeroGPU, quota limited)
#   3. None — pipeline_avatar falls back to hybrid pipeline

# Avatar styles (for AI-generated faces):
#   doctor     — Nigerian female/male doctor, white coat, warm clinical setting
#   presenter  — Sharp news presenter, studio background, authoritative
#   friend     — Young Nigerian, casual wear, natural light, TikTok vibe

# Install:
#   pip install gradio_client huggingface_hub
# """

# import asyncio
# import io
# from pathlib import Path
# from typing import Optional
# from config import HF_API_KEY, OUTPUT_DIR

# # ─── HF Space endpoints ───────────────────────────────────────────────────────
# WAV2LIP_SPACE_PRIMARY   = "manavisrani07/gradio-lipsync-wav2lip"
# WAV2LIP_SPACE_SECONDARY = "pragnakalp/Wav2lip-ZeroGPU"

# # ─── Avatar style → FLUX image prompt ────────────────────────────────────────
# AVATAR_STYLE_PROMPTS = {
#     "doctor": (
#         "Professional Nigerian female doctor, mid-30s, warm smile, "
#         "white medical coat, stethoscope, clean clinic background, "
#         "soft studio lighting, high quality portrait, 576x1024, "
#         "photorealistic, looking directly at camera, neutral expression"
#     ),
#     "presenter": (
#         "Professional Nigerian news presenter, confident expression, "
#         "smart blazer, modern studio background with soft bokeh, "
#         "broadcast lighting, high quality portrait, 576x1024, "
#         "photorealistic, looking directly at camera"
#     ),
#     "friend": (
#         "Young Nigerian content creator, casual stylish outfit, "
#         "natural warm light, friendly smile, clean home background, "
#         "high quality portrait, 576x1024, photorealistic, "
#         "looking directly at camera, relatable and approachable"
#     ),
# }

# DEFAULT_STYLE = "doctor"

# # ─── Timeouts ─────────────────────────────────────────────────────────────────
# WAV2LIP_PRIMARY_TIMEOUT   = 180.0
# WAV2LIP_SECONDARY_TIMEOUT = 120.0
# FACE_GEN_TIMEOUT          = 60.0


# # ─── Public interface ─────────────────────────────────────────────────────────

# async def generate_avatar_video(
#     audio_path: Path,
#     job_id: str,
#     face_image_path: Optional[Path] = None,
#     avatar_style: str = DEFAULT_STYLE,
# ) -> Optional[Path]:
#     """
#     Main entry point. Returns Path to animated MP4 or None on failure.

#     Args:
#         audio_path:       Voiceover MP3/WAV (already generated by audio.py)
#         job_id:           For output file naming
#         face_image_path:  PREMIUM — user uploaded image path
#                           None    — FREE, generate face with FLUX
#         avatar_style:     "doctor" | "presenter" | "friend"
#     """
#     if not HF_API_KEY:
#         print("[avatar] HF_API_KEY not set — skipping avatar generation")
#         return None

#     # Step 1: Resolve face image
#     if face_image_path and face_image_path.exists():
#         face_path = face_image_path
#         print(f"[avatar] Using uploaded face: {face_path.name}")
#     else:
#         print(f"[avatar] Generating AI face (style: {avatar_style})…")
#         face_path = await _generate_face_image(job_id, avatar_style)
#         if not face_path:
#             print("[avatar] Face generation failed — cannot proceed")
#             return None

#     # Step 2: Animate — Wav2Lip primary → Wav2Lip secondary → None
#     output_path = OUTPUT_DIR / f"{job_id}_avatar.mp4"

#     result = await _try_wav2lip(
#         face_path, audio_path, output_path,
#         space=WAV2LIP_SPACE_PRIMARY,
#         timeout=WAV2LIP_PRIMARY_TIMEOUT,
#         label="Wav2Lip primary",
#     )
#     if result:
#         print(f"[avatar] ✓ Wav2Lip (primary) succeeded → {output_path.name}")
#         return result

#     print("[avatar] Primary failed — trying Wav2Lip secondary…")
#     result = await _try_wav2lip(
#         face_path, audio_path, output_path,
#         space=WAV2LIP_SPACE_SECONDARY,
#         timeout=WAV2LIP_SECONDARY_TIMEOUT,
#         label="Wav2Lip secondary",
#     )
#     if result:
#         print(f"[avatar] ✓ Wav2Lip (secondary) succeeded → {output_path.name}")
#         return result

#     print("[avatar] Both Wav2Lip spaces failed — pipeline will use hybrid fallback")
#     return None


# # ─── Face generation (FLUX via HF SDK) ───────────────────────────────────────

# async def _generate_face_image(job_id: str, style: str) -> Optional[Path]:
#     """Generates a portrait face image using FLUX.1-schnell via HF SDK."""
#     try:
#         from huggingface_hub import AsyncInferenceClient

#         prompt = AVATAR_STYLE_PROMPTS.get(style, AVATAR_STYLE_PROMPTS[DEFAULT_STYLE])
#         client = AsyncInferenceClient(provider="hf-inference", api_key=HF_API_KEY)

#         pil_image = await asyncio.wait_for(
#             client.text_to_image(
#                 prompt=prompt,
#                 model="black-forest-labs/FLUX.1-schnell",
#                 width=576,
#                 height=1024,
#                 num_inference_steps=4,
#             ),
#             timeout=FACE_GEN_TIMEOUT,
#         )

#         face_path = OUTPUT_DIR / f"{job_id}_face.jpg"
#         buf = io.BytesIO()
#         pil_image.save(buf, format="JPEG", quality=95)
#         face_path.write_bytes(buf.getvalue())
#         print(f"[avatar] ✓ Face generated → {face_path.name}")
#         return face_path

#     except asyncio.TimeoutError:
#         print("[avatar] Face generation timed out")
#         return None
#     except Exception as e:
#         print(f"[avatar] Face generation failed: {e}")
#         return None


# # ─── Wav2Lip animator (works for both spaces) ─────────────────────────────────

# async def _try_wav2lip(
#     face_path: Path,
#     audio_path: Path,
#     output_path: Path,
#     space: str,
#     timeout: float,
#     label: str,
# ) -> Optional[Path]:
#     """
#     Calls a Wav2Lip HF Space via gradio_client.
#     Runs in thread executor so it doesn't block the async loop.
#     Both target spaces accept (image, audio) and return a video file.
#     """
#     try:
#         result = await asyncio.wait_for(
#             asyncio.get_event_loop().run_in_executor(
#                 None,
#                 _wav2lip_sync,
#                 face_path,
#                 audio_path,
#                 output_path,
#                 space,
#             ),
#             timeout=timeout,
#         )
#         return result
#     except asyncio.TimeoutError:
#         print(f"[avatar] {label} timed out after {timeout}s")
#         return None
#     except Exception as e:
#         print(f"[avatar] {label} error: {e}")
#         return None


# def _wav2lip_sync(
#     face_path: Path,
#     audio_path: Path,
#     output_path: Path,
#     space: str,
# ) -> Optional[Path]:
#     """
#     Synchronous Wav2Lip call (runs in thread executor).

#     Both manavisrani07/gradio-lipsync-wav2lip and pragnakalp/Wav2lip-ZeroGPU
#     expose a predict endpoint that takes:
#       - face: image file (portrait photo)
#       - audio: audio file (MP3/WAV)
#     and returns a video file path.

#     We try the standard api_name first, then fall back to index-based call.
#     """
#     try:
#         from gradio_client import Client, handle_file

#         client = Client(space, hf_token=HF_API_KEY)

#         # Try named API endpoint first
#         try:
#             result = client.predict(
#                 face=handle_file(str(face_path)),
#                 audio=handle_file(str(audio_path)),
#                 api_name="/predict",
#             )
#         except Exception:
#             # Fall back to positional args (some spaces use different param names)
#             result = client.predict(
#                 handle_file(str(face_path)),
#                 handle_file(str(audio_path)),
#                 api_name="/predict",
#             )

#         # Result can be a path string, dict with 'video', or a tuple
#         video_src = _extract_video_path(result)

#         if video_src and Path(str(video_src)).exists():
#             output_path.write_bytes(Path(str(video_src)).read_bytes())
#             return output_path

#         print(f"[avatar] {space} returned unexpected result type: {type(result)}")
#         return None

#     except Exception as e:
#         print(f"[avatar] {space} sync error: {e}")
#         return None


# def _extract_video_path(result) -> Optional[str]:
#     """
#     Extracts a video file path from various result formats gradio_client returns.
#     Handles: str, dict with 'video'/'output'/'path', tuple, list.
#     """
#     if isinstance(result, str):
#         return result
#     if isinstance(result, dict):
#         for key in ("video", "output", "path", "file"):
#             if key in result:
#                 v = result[key]
#                 return v if isinstance(v, str) else (v.get("path") if isinstance(v, dict) else None)
#     if isinstance(result, (list, tuple)) and len(result) > 0:
#         first = result[0]
#         if isinstance(first, str):
#             return first
#         if isinstance(first, dict):
#             return first.get("video") or first.get("path")
#     return None


# # ─── Utility ──────────────────────────────────────────────────────────────────

# def is_premium_request(face_image_path: Optional[Path]) -> bool:
#     """Returns True if this is a premium (user photo) request."""
#     return face_image_path is not None and face_image_path.exists()


# def get_available_styles() -> list[dict]:
#     """Returns avatar style options for the frontend."""
#     return [
#         {
#             "id": "doctor",
#             "label": "Medical Doctor",
#             "description": "Professional doctor in white coat — ideal for health content",
#             "tier": "free",
#         },
#         {
#             "id": "presenter",
#             "label": "News Presenter",
#             "description": "Authoritative news anchor — great for announcements",
#             "tier": "free",
#         },
#         {
#             "id": "friend",
#             "label": "Friendly Host",
#             "description": "Casual relatable creator — perfect for TikTok",
#             "tier": "free",
#         },
#         {
#             "id": "custom",
#             "label": "Your Own Face",
#             "description": "Upload your photo and make it talk",
#             "tier": "premium",
#         },
#     ]



"""
services/avatar.py  —  Talking Avatar Service (Local Wav2Lip)
═══════════════════════════════════════════════════════════════════════════════

Runs Wav2Lip locally via subprocess — no API dependency, no rate limits.

Setup (one-time):
  cd backend
  git clone https://github.com/Rudrabha/Wav2Lip.git wav2lip
  cd wav2lip && pip install -r requirements.txt
  mkdir -p checkpoints
  wget "https://huggingface.co/numz/wav2lip_studio/resolve/main/checkpoints/wav2lip_gan.pth" \
       -O checkpoints/wav2lip_gan.pth

Directory structure expected:
  backend/
    wav2lip/
      inference.py
      checkpoints/
        wav2lip_gan.pth

Two modes:
  FREE    — FLUX.1 generates a face image, Wav2Lip animates it
  PREMIUM — User uploads their own photo, Wav2Lip animates it
"""

import asyncio
import io
import subprocess
from pathlib import Path
from typing import Optional
from config import HF_API_KEY, OUTPUT_DIR

# ─── Wav2Lip local path ───────────────────────────────────────────────────────
# Relative to wherever uvicorn is launched from (your backend/ folder)
WAV2LIP_DIR        = Path(__file__).parent.parent / "wav2lip"
WAV2LIP_INFERENCE  = WAV2LIP_DIR / "inference.py"
WAV2LIP_CHECKPOINT = WAV2LIP_DIR / "checkpoints" / "wav2lip_gan.pth"

# ─── Avatar style prompts ─────────────────────────────────────────────────────
AVATAR_STYLE_PROMPTS = {
    "doctor": (
        "Professional Nigerian female doctor, mid-30s, warm smile, "
        "white medical coat, stethoscope, clean clinic background, "
        "soft studio lighting, high quality portrait, "
        "photorealistic, looking directly at camera, neutral expression, "
        "face clearly visible, front-facing, no sunglasses"
    ),
    "presenter": (
        "Professional Nigerian news presenter, confident expression, "
        "smart blazer, modern studio background with soft bokeh, "
        "broadcast lighting, high quality portrait, "
        "photorealistic, looking directly at camera, "
        "face clearly visible, front-facing"
    ),
    "friend": (
        "Young Nigerian content creator, casual stylish outfit, "
        "natural warm light, friendly smile, clean home background, "
        "high quality portrait, photorealistic, "
        "looking directly at camera, relatable and approachable, "
        "face clearly visible, front-facing"
    ),
}

DEFAULT_STYLE    = "doctor"
FACE_GEN_TIMEOUT = 60.0
WAV2LIP_TIMEOUT  = 300.0   # local inference can take 1-4 min depending on audio length


# ─── Public interface ─────────────────────────────────────────────────────────

async def generate_avatar_video(
    audio_path: Path,
    job_id: str,
    face_image_path: Optional[Path] = None,
    avatar_style: str = DEFAULT_STYLE,
) -> Optional[Path]:
    """
    Main entry point. Returns Path to animated MP4 or None on failure.

    Args:
        audio_path:       Voiceover MP3 (already generated by audio.py)
        job_id:           For output file naming
        face_image_path:  PREMIUM — user uploaded image path
                          None    — FREE, generate face with FLUX
        avatar_style:     "doctor" | "presenter" | "friend"
    """
    # Check Wav2Lip is installed
    if not WAV2LIP_INFERENCE.exists():
        print(
            "[avatar] wav2lip/inference.py not found.\n"
            "         Run: git clone https://github.com/Rudrabha/Wav2Lip.git wav2lip\n"
            "         Then download the checkpoint — see services/avatar.py header."
        )
        return None

    if not WAV2LIP_CHECKPOINT.exists():
        print(
            f"[avatar] Checkpoint not found: {WAV2LIP_CHECKPOINT}\n"
            "         Download from: https://huggingface.co/numz/wav2lip_studio/resolve/main/checkpoints/wav2lip_gan.pth"
        )
        return None

    # Step 1: resolve face image
    if face_image_path and face_image_path.exists():
        face_path = face_image_path
        print(f"[avatar] Using uploaded face: {face_path.name}")
    else:
        print(f"[avatar] Generating AI face (style: {avatar_style})…")
        face_path = await _generate_face_image(job_id, avatar_style)
        if not face_path:
            print("[avatar] Face generation failed")
            return None

    # Step 2: run Wav2Lip
    return await _run_wav2lip(face_path, audio_path, job_id)


# ─── Face generation (FLUX via HF SDK) ───────────────────────────────────────

async def _generate_face_image(job_id: str, style: str) -> Optional[Path]:
    """Generates a portrait using FLUX.1-schnell via HF SDK."""
    if not HF_API_KEY:
        print("[avatar] HF_API_KEY not set — cannot generate face image")
        return None

    try:
        from huggingface_hub import AsyncInferenceClient

        prompt = AVATAR_STYLE_PROMPTS.get(style, AVATAR_STYLE_PROMPTS[DEFAULT_STYLE])
        client = AsyncInferenceClient(provider="hf-inference", api_key=HF_API_KEY)

        pil_image = await asyncio.wait_for(
            client.text_to_image(
                prompt=prompt,
                model="black-forest-labs/FLUX.1-schnell",
                width=576,
                height=768,        # slightly less tall than 1024 — better for faces
                num_inference_steps=4,
            ),
            timeout=FACE_GEN_TIMEOUT,
        )

        face_path = OUTPUT_DIR / f"{job_id}_face.jpg"
        buf = io.BytesIO()
        pil_image.save(buf, format="JPEG", quality=95)
        face_path.write_bytes(buf.getvalue())
        print(f"[avatar] ✓ Face generated → {face_path.name}")
        return face_path

    except asyncio.TimeoutError:
        print("[avatar] Face generation timed out")
        return None
    except Exception as e:
        print(f"[avatar] Face generation failed: {e}")
        return None


# ─── Local Wav2Lip subprocess ─────────────────────────────────────────────────

async def _run_wav2lip(
    face_path: Path,
    audio_path: Path,
    job_id: str,
) -> Optional[Path]:
    """
    Runs Wav2Lip inference as a subprocess.
    Wav2Lip requires the face to be a clear front-facing image or short video.
    Output is always written to OUTPUT_DIR/{job_id}_avatar.mp4.
    """
    output_path = OUTPUT_DIR / f"{job_id}_avatar.mp4"

    try:
        result = await asyncio.wait_for(
            asyncio.get_event_loop().run_in_executor(
                None,
                _wav2lip_subprocess,
                face_path,
                audio_path,
                output_path,
            ),
            timeout=WAV2LIP_TIMEOUT,
        )
        return result
    except asyncio.TimeoutError:
        print(f"[avatar] Wav2Lip timed out after {WAV2LIP_TIMEOUT}s")
        return None
    except Exception as e:
        print(f"[avatar] Wav2Lip failed: {e}")
        return None


def _wav2lip_subprocess(
    face_path: Path,
    audio_path: Path,
    output_path: Path,
) -> Optional[Path]:
    """
    Synchronous Wav2Lip subprocess call.

    Key flags:
      --face        input image or video
      --audio       input audio (MP3/WAV)
      --outfile     output MP4
      --checkpoint  model weights path
      --nosmooth    skip temporal smoothing (faster, fine for images)
      --resize_factor 1   keep original resolution
      --pads 0 10 0 0     add 10px padding below chin (improves lip visibility)
    """
    cmd = [
        "python3", str(WAV2LIP_INFERENCE),
        "--checkpoint_path", str(WAV2LIP_CHECKPOINT),
        "--face", str(face_path),
        "--audio", str(audio_path),
        "--outfile", str(output_path),
        "--nosmooth",
        "--resize_factor", "1",
        "--pads", "0", "10", "0", "0",
    ]

    print(f"[avatar] Running Wav2Lip: {' '.join(cmd)}")

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        cwd=str(WAV2LIP_DIR),   # run from wav2lip/ dir so relative imports work
    )

    if result.returncode != 0:
        print(f"[avatar] Wav2Lip stderr:\n{result.stderr[-800:]}")
        return None

    if output_path.exists() and output_path.stat().st_size > 10_000:
        print(f"[avatar] ✓ Wav2Lip done → {output_path.name}")
        return output_path

    print("[avatar] Wav2Lip completed but output file is missing or too small")
    return None


# ─── Utility ──────────────────────────────────────────────────────────────────

def is_wav2lip_ready() -> bool:
    """Call this from /health to surface setup issues early."""
    return WAV2LIP_INFERENCE.exists() and WAV2LIP_CHECKPOINT.exists()


def is_premium_request(face_image_path: Optional[Path]) -> bool:
    return face_image_path is not None and face_image_path.exists()


def get_available_styles() -> list[dict]:
    return [
        {
            "id": "doctor",
            "label": "Medical Doctor",
            "description": "Professional doctor in white coat — ideal for health content",
            "tier": "free",
        },
        {
            "id": "presenter",
            "label": "News Presenter",
            "description": "Authoritative news anchor — great for announcements",
            "tier": "free",
        },
        {
            "id": "friend",
            "label": "Friendly Host",
            "description": "Casual relatable creator — perfect for TikTok",
            "tier": "free",
        },
        {
            "id": "custom",
            "label": "Your Own Face",
            "description": "Upload your photo and make it talk",
            "tier": "premium",
        },
    ]